defaults:
  - /path: __task__
  - /module: __init__
  - /pipeline@pipeline: dataset_preprocessing

_config_name_: datasets
project: ${oc.select:project,null}
task_name: dataset
task_root: ${oc.select:project.path.project_workspace_root,workspace/tasks}/${.task_name}
autoload: false
version: "0.0.0"
pipelines:
  - pipeline
