defaults:
  - __dataframe_external_funcs__

run:
  _target_: hyfi.main.HyFI.load_dataframes
  data_files:
  data_dir:
  filetype:
  split:
  concatenate: false
  ignore_index: false
  use_cached: false
  verbose: true
use_pipe_obj: false
