defaults:
  - __dataframe_external_funcs__

run:
  _target_: hyfi.main.HyFI.save_dataframes
  data:
  data_file:
  data_dir:
  columns:
  index: false
  filetype: parquet
  suffix:
  verbose: true
pipe_obj_arg_name: data
return_pipe_obj: true
